# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20191014_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFormRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
    ]
